/* generated configuration header file - do not edit */
#ifndef BSP_PIN_CFG_H_
#define BSP_PIN_CFG_H_
#include "r_ioport.h"

/* Common macro for FSP header files. There is also a corresponding FSP_FOOTER macro at the end of this file. */
FSP_HEADER

#define IO_CFG_INT (BSP_IO_PORT_00_PIN_00)
#define ARDUINO_A0 (BSP_IO_PORT_00_PIN_01)
#define GROVE2_1_AN0 (BSP_IO_PORT_00_PIN_02) /* Reference E42 / E39 User Manual */
#define ARDUINO_A2 (BSP_IO_PORT_00_PIN_03)
#define ARDUINO_A3 (BSP_IO_PORT_00_PIN_04)
#define GROVE2_2_AN1 (BSP_IO_PORT_00_PIN_05) /* Reference E41 / E40 User Manual */
#define PMOD1_7_IRQ11_DS (BSP_IO_PORT_00_PIN_06)
#define ARDUINO_A1 (BSP_IO_PORT_00_PIN_07)
#define USER_S2 (BSP_IO_PORT_00_PIN_08) /* Reference E32 User Manual */
#define USER_S1 (BSP_IO_PORT_00_PIN_09) /* Reference E31 User Manual */
#define MIKROBUS_IRQ14 (BSP_IO_PORT_00_PIN_10)
#define ARDUINO_D2 (BSP_IO_PORT_00_PIN_11)
#define PMOD2_7_IRQ15 (BSP_IO_PORT_00_PIN_12)
#define ARDUINO_A4 (BSP_IO_PORT_00_PIN_14)
#define ARDUINO_A5 (BSP_IO_PORT_00_PIN_15)
#define OSPI_SIO0 (BSP_IO_PORT_01_PIN_00)
#define OSPI_SIO3 (BSP_IO_PORT_01_PIN_01)
#define OSPI_SIO4 (BSP_IO_PORT_01_PIN_02)
#define OSPI_SIO2 (BSP_IO_PORT_01_PIN_03)
#define OSPI_CS_L (BSP_IO_PORT_01_PIN_04) /* Reference E8 User Manual */
#define OSPI_ECS_L (BSP_IO_PORT_01_PIN_05)
#define OSPI_RES_L (BSP_IO_PORT_01_PIN_06)
#define I3C_SDA_PULL_UP (BSP_IO_PORT_01_PIN_09) /* See I2C/I3C Pullup Configuration in User Manual */
#define ARDUINO_D9 (BSP_IO_PORT_01_PIN_10)
#define MIKROBUS_RESET_L (BSP_IO_PORT_01_PIN_11)
#define JTAG_SWD_TDI (BSP_IO_PORT_02_PIN_08)
#define JTAG_SWD_TDO (BSP_IO_PORT_02_PIN_09)
#define JTAG_SWD_TMS (BSP_IO_PORT_02_PIN_10)
#define JTAG_SWD_CLK (BSP_IO_PORT_02_PIN_11)
#define TRACE_TDATA3 (BSP_IO_PORT_03_PIN_04)
#define TRACE_TDATA2 (BSP_IO_PORT_03_PIN_05)
#define TRACE_TDATA1 (BSP_IO_PORT_03_PIN_06)
#define TRACE_TDATA0 (BSP_IO_PORT_03_PIN_07)
#define TRACE_TCLK (BSP_IO_PORT_03_PIN_08)
#define ARDUINO_D7 (BSP_IO_PORT_03_PIN_12)
#define I3C_SCL0_BOARD_DEVICES (BSP_IO_PORT_04_PIN_00) /* See I2C/I3C Pullup Configuration in User Manual */
#define I3C_SDA0_BOARD_DEVICES (BSP_IO_PORT_04_PIN_01) /* See I2C/I3C Pullup Configuration in User Manual */
#define ETHERNET_LINKSTA (BSP_IO_PORT_04_PIN_02) /* Reference E18 / E34 User Manual */
#define PMOD1_8_RESET (BSP_IO_PORT_04_PIN_03)
#define ETHERNET_RX_CTL (BSP_IO_PORT_04_PIN_05)
#define ETHERNET_RXD3 (BSP_IO_PORT_04_PIN_06)
#define USBFS_VBUS (BSP_IO_PORT_04_PIN_07)
#define USBHS_VBUS (BSP_IO_PORT_04_PIN_08)
#define PMOD2_9_GPIO (BSP_IO_PORT_04_PIN_09)
#define PMOD2_8_GPIO (BSP_IO_PORT_04_PIN_10)
#define PMOD1_9_GPIO (BSP_IO_PORT_04_PIN_12)
#define PMOD1_10_GPIO (BSP_IO_PORT_04_PIN_13)
#define ARDUINO_D10_MIKROBUS_CS (BSP_IO_PORT_04_PIN_14)
#define ARDUINO_D13_MIKROBUS_SCK (BSP_IO_PORT_04_PIN_15)
#define USBFS_VBUS_SEL (BSP_IO_PORT_05_PIN_00)
#define ARDUINO_D6 (BSP_IO_PORT_05_PIN_09)
#define ARDUINO_D5 (BSP_IO_PORT_05_PIN_10)
#define I2C_SDA1_SYSTEM_DEVICES (BSP_IO_PORT_05_PIN_11) /* Reference E40 User Manual */
#define I2C_SCL1_SYSTEM_DEVICES (BSP_IO_PORT_05_PIN_12) /* Reference E39 User Manual */
#define ETHERNET_NRESET (BSP_IO_PORT_05_PIN_14)
#define PMOD2_4_SCK (BSP_IO_PORT_06_PIN_01) /* Reference E14 / E16 User Manual */
#define PMOD2_3_MISO_RXD (BSP_IO_PORT_06_PIN_02)
#define PMOD2_2_MOSI_TXD (BSP_IO_PORT_06_PIN_03)
#define PMOD2_1_CTS_RTS_SSL (BSP_IO_PORT_06_PIN_04) /* Reference E14 / E15 User Manual */
#define PMOD2_1_CTS (BSP_IO_PORT_06_PIN_05) /* Reference E10 / E15 User Manual */
#define ETHERNET_RXD2 (BSP_IO_PORT_07_PIN_00)
#define ETHERNET_RXD1 (BSP_IO_PORT_07_PIN_01)
#define ETHERNET_RXD0 (BSP_IO_PORT_07_PIN_02)
#define ETHERNET_RXD_CLK (BSP_IO_PORT_07_PIN_03)
#define PMOD2_10_GPIO (BSP_IO_PORT_07_PIN_04)
#define ETHERNET_TX_CTL (BSP_IO_PORT_07_PIN_05)
#define ETHERNET_TX_CLK (BSP_IO_PORT_07_PIN_06)
#define ARDUINO_D11_MIKROBUS_MOSI (BSP_IO_PORT_07_PIN_08)
#define ARDUINO_D12_MIKROBUS_MISO (BSP_IO_PORT_07_PIN_09)
#define ARDUINO_RESET_L (BSP_IO_PORT_07_PIN_10)
#define USER_LED1_BLUE (BSP_IO_PORT_07_PIN_11) /* Reference E27 User Manual */
#define USER_LED2_GREEN (BSP_IO_PORT_07_PIN_13) /* Reference E26 User Manual */
#define OSPI_SIO5 (BSP_IO_PORT_08_PIN_00)
#define OSPI_DQS (BSP_IO_PORT_08_PIN_01)
#define OSPI_SIO6 (BSP_IO_PORT_08_PIN_02)
#define OSPI_SIO1 (BSP_IO_PORT_08_PIN_03)
#define OSPI_SIO7 (BSP_IO_PORT_08_PIN_04)
#define OSPI_CLK (BSP_IO_PORT_08_PIN_08)
#define ARDUINO_D4 (BSP_IO_PORT_08_PIN_10)
#define ARDUINO_D3 (BSP_IO_PORT_08_PIN_11)
#define USBFS_P (BSP_IO_PORT_08_PIN_14)
#define USBFS_M (BSP_IO_PORT_08_PIN_15)
#define CANFD_STBY (BSP_IO_PORT_09_PIN_07)
#define CANFD_RXD (BSP_IO_PORT_09_PIN_08)
#define CANFD_TXD (BSP_IO_PORT_09_PIN_09)
#define I3C_SCL_PULL_UP (BSP_IO_PORT_09_PIN_11) /* See I2C/I3C Pullup Configuration in User Manual */
#define PMOD1_3_RXD2_MISO2 (BSP_IO_PORT_10_PIN_02)
#define PMOD1_2_TXD2_MOSI2_RST (BSP_IO_PORT_10_PIN_03)
#define PMOD1_4_SCK2 (BSP_IO_PORT_10_PIN_04)
#define PMOD1_1_CTS_RTS2_SS2 (BSP_IO_PORT_10_PIN_05)
#define PMOD1_1_CTS2 (BSP_IO_PORT_10_PIN_06)
#define USER_LED3_RED (BSP_IO_PORT_10_PIN_07) /* Reference E28 User Manual */
#define MODBUS_RO_RX5 (BSP_IO_PORT_10_PIN_08)
#define MODBUS_DI_TX5 (BSP_IO_PORT_10_PIN_09)
#define MODBUS_RE_DE_DE5 (BSP_IO_PORT_10_PIN_10)
#define ETHERNET_TXD0 (BSP_IO_PORT_11_PIN_00)
#define ETHERNET_TXD1 (BSP_IO_PORT_11_PIN_02)
#define ETHERNET_TXD2 (BSP_IO_PORT_11_PIN_03)
#define ETHERNET_TXD3 (BSP_IO_PORT_11_PIN_04)
#define ARDUINO_D1_MIKROBUS_TXD7 (BSP_IO_PORT_12_PIN_03)
#define ARDUINO_D0_MIKROBUS_RXD7 (BSP_IO_PORT_12_PIN_04)
#define ETHERNET_MDC (BSP_IO_PORT_12_PIN_11)
#define ETHERNET_MDIO (BSP_IO_PORT_12_PIN_12)
#define ETHERNET_MDINT (BSP_IO_PORT_12_PIN_13)
#define ARDUINO_D8 (BSP_IO_PORT_13_PIN_01)
#define VCOMM_TXD_TO_EXT (BSP_IO_PORT_13_PIN_02)
#define VCOMM_RXD_FROM_EXT (BSP_IO_PORT_13_PIN_03)
#define VCOMM_RTS_FROM_EXT (BSP_IO_PORT_13_PIN_04) /* Reference E17 User Manual */
#define VCOMM_CTS_TO_EXT (BSP_IO_PORT_13_PIN_05) /* Reference E9 User Manual */
#define USB_HS_VBUSEN (BSP_IO_PORT_13_PIN_07)

extern const ioport_cfg_t g_bsp_pin_cfg; /* R7KA8M2JFLCAC.pincfg */

void BSP_PinConfigSecurityInit();

/* Common macro for FSP header files. There is also a corresponding FSP_HEADER macro at the top of this file. */
FSP_FOOTER
#endif /* BSP_PIN_CFG_H_ */
